FROM python:3.14-slim

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY accountant.py .

EXPOSE 3001
CMD ["python", "-m", "flask", "--app", "accountant.py", "run", "--host", "0.0.0.0", "--port", "3001"]