FROM python:3.14-slim

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY gamer.py .
COPY static ./static/

EXPOSE 3003
CMD ["python", "-m", "flask", "--app", "gamer.py", "run", "--host", "0.0.0.0", "--port", "3003"]