FROM python:3.14-slim

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY lobster.py .

EXPOSE 3002
CMD ["python", "-m", "flask", "--app", "lobster.py", "run", "--host", "0.0.0.0", "--port", "3002"]